### ISSUE TITLE
No reading any tempeerature

### ISSUE THREAD

**Issue by dbpp31** [sparkfun/SparkFun_MLX90632_Arduino_Library#2]
I have connected the sensor to an Arduino mega 2560.
I added the library by using the Arduino 1.8.5 version.
Then I tried the example1 and example2 from the library, however, I have the following result:
"MLX90632 Read Example
Object Temperature: 0.00 C
Object Temperature: 0.00 C"

I have checked the "pull request" and then I modified the keywords on the library SparkFun_MLX90632_Arduino_Library. Now I have highlighted the word "MLX90632" on the example1.ino. Even that, my result is the same. I cannot read the temperature using the sensor.

In case of example 2, I have the same result.

"MLX90632 Read Example
Object Temperature: 32.00 F Sensor Temperature: 0.00 C
Object Temperature: 32.00 F Sensor Temperature: 0.00 C"

Moreover, I have checked with a multimeter the voltage on the pines of the sensor. I have the correct voltage between 3.3V and GND. In case of SCL and SDA, I know it is not constant because of the transmission of data, so I measured to see if there is any voltage related to the data, there was around 3.1V. in each pin.  It means there is data on the pins and the welding between the pins and the sensor module is correct ( Also I verified the continuity on the board and the pins).

Therefore. I have no idea what can be the problem.
Help, please!!!!!!

**Comment by nseidle** [comment]
Hi,

* What board for the MLX90632 are you using? 
* Do you have pull up resistors on your I2C lines?

**Comment by dbpp31** [comment]
Hi nseidle. 
Thank you for your reply!!!
I am using this module: Infrared Non-contact Thermometer (Qwiic) - MLX90632, https://www.sparkfun.com/products/14569

According to the schematic of that module, it has the resistors on the I2C lines. However, I also tried but adding the pull up by myself. Between the sensor mudle and the arduino, I am using also a level shifter from 3.3 and 5v.  Although there is a voltage on SDA and SCL, the measurement is still completely null.

When I run the example4. Debug printing from the library, I have the following result:

I2C Error: No read response
I2C Error: End transmission

Then, I still have no idea what can be the problem. How can I know that the temperature sensor by itself is not damaged or is working correctly?

Thank you!!!

**Comment by nseidle** [comment]
Good. That board has pull ups on it so you shouldn't need to add them.

What platform are you connecting it to? How is it connected?

**Comment by dbpp31** [comment]
Hi nseidle.
Thank you for your reply!!!
I tried to connect to an arduino Uno and arduino Mega. In both cases, I have the same results: a null reading.

The wire connections are:
-the wire between Arduino-SCL and Levelshifter HV1
-the wire between Arduino-SDA and Levelshifter HV2
-the wire between SensorMLX90632-SCL and Levelshifter LV1
-the wire between SensorMLX90632-SDA and Levelshifter LV2

-the wire between Arduino-5V and Levelshifter HV
-the wire between Arduino-3.3V and Levelshifter LV
-the wire between Arduino-GND and Levelshifter GND
-the wire between SensorMLX90632-GND and Levelshifter GND

As an illustration, the connection  is pretty similar to this image, except the following wires:

-the wire between Arduino-PIN2 and Levelshifter HV1
-the wire between Arduino-PIN3 and Levelshifter HV2
-the wire between Levelshifter LV1 and Sensor X1-Int1
-the wire between Levelshifter LV2 and Sensor X2-Int1

![5266e578757b7fe84c8b456f](https://user-images.githubusercontent.com/40269007/41989709-29b68cd6-7a7b-11e8-8e51-07def89299eb.png)


I think there is not a mistake on the wire connection. I hope you can check it and tell me if there is ane mistake.
Thanks in advance.

**Comment by nseidle** [comment]
Hmm. That wiring looks fine. I suspect there is a problem with our board. Please contact [tech support](https://www.sparkfun.com/technical_assistance) and link to this page conversation. I'll authorize a replacement once we have your order # (so we can get the address to ship the replacement).

**Comment by dbpp31** [comment]
Thank you, I will proceed as your instructions. 
In addition, Could you also update and make a double check on the code of the library. There is an open "pull request". I also followed those instructions to update the "keywords" file. I am thinking if the sensor that I received is ok, then maybe there is still a mistake on the library.
Thanks in advance.

*Attached to this, there is the modified "keyword" file that I made.
[keywords.txt](https://github.com/sparkfun/SparkFun_MLX90632_Arduino_Library/files/2142328/keywords.txt)

**Comment by nseidle** [comment]
The keywords file does not affect the library. It only controls the highlighting of words in the Arduino IDE.

The PR has been accepted (thanks for pointing that out!) but the library has been in use for over 6 months by many other people without issue. Sounds like you have a hardware issue so I'm closing this issue out. Please re-open if you continue to experience problems with the replacement board.

**Comment by suyihmeei** [comment]
![messageImage_1650443400273](https://user-images.githubusercontent.com/35685948/164199589-7a349ea1-8c43-4b78-a44c-d4cee8147890.jpeg)
