### ISSUE TITLE
How to increase the speed of reading the object temperature?

### ISSUE THREAD

**Issue by dbpp31** [sparkfun/SparkFun_MLX90632_Arduino_Library#3]
I am using the "Example 1" file.  The sensor is working correctly. however, I would like to increase the speed of printing on the serial port the "reading of the object temperature". I cannot find where to modify the configuration to have a faster reading.
I mean,  I would like to have a reading, for example, each 10ms. However, if I just compile the lines of the "Example 1", even there is not any "delay" command. the print on the serial port is not fast, maybe it is each  500ms.

Thank you in advance.

**Comment by nseidle** [comment]
Our [example 3](https://github.com/sparkfun/SparkFun_MLX90640_Arduino_Example/blob/master/Firmware/Example3_MaxRefreshRate/Example3_MaxRefreshRate.ino) covers this pretty well. Every 10ms is not possible using I2C. ~250ms is about the fastest you can read each image frame. There is a large amount of image data being transmitted from the sensor to your processor over I2C (400kHz). I2C is kind of a bottleneck.
