### ISSUE TITLE
MLX90632_Arduino_Library working issue with ESP32-S2

### ISSUE THREAD

**Issue by Dvl-s** [sparkfun/SparkFun_MLX90632_Arduino_Library#6]
Hii, Sparkfun Team

IDE : Arduino IDE ver 1.8.23
Board : ESP32-S2
I2c Pins : SDA (8), SCL(9)

The MLX90632 Library can not working with ESP32-S2. Although I2C is working ok. so please suggest if any information to make this library working with ESP32 S2. This Library is working good with ESP32.

**Comment by nseidle** [comment]
Similar to issue reported for the [MLX90640](https://github.com/sparkfun/SparkFun_MLX90640_Arduino_Example/issues/24).

**Comment by nseidle** [comment]
Pull the latest changes to the ESP32 Arduino core and it should fix the problem.
